Proj 1 vector operations
OlegShchegolev/made-cpp-2020-hw pull request #3
Opened 2020-09-24 12:06 UTC by OlegShchegolev

2020-10-08 19:34 UTC, xterrafunny requested changes

2020-10-08 19:34 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    double div = lhs[0] / rhs[0];
Почему `rhs[0] != 0`?

2020-10-08 19:34 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        if ((lhs[i] / rhs[i] - div > 1e-8) || (lhs[i] / rhs[i] - div < -1e-8))
`1e-8` - magic const

2020-10-08 19:34 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    if ((lhs || rhs) && lhs[0] / rhs[0] >= 0)
Проверка на ноль

2020-10-08 19:34 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +        v[v.size() - i - 1] = tmp;
Есть `std::swap`

2020-10-10 11:30 UTC, OlegShchegolev commented
Спасибо! Исправил, проверьте, пожалуйста

2020-10-29 15:25 UTC, merged